### ISSUE TITLE
가이드 봇 만들기

### ISSUE THREAD

**Issue by tribela** [mstdn-kr/mastodon-kr#2]
<del>
- [ ] 신규 유저 발견시 가이드 페이지 (#1) 링크와 함께 멘션
  - [ ] 발견하지 못 했어도 기존 유저가 멘션과 해시태그를 통해 유도
- [ ] 키워드와 함께 멘션을 받으면 관련 된 정보를 답장
</del>

---

- [ ] 멘션을 받으면 도우미에게 DM으로 포워딩
 - [ ] 해당 스레드에 도우미가 답을 달면 질문자에게 포워딩
 - [ ] 예외상황(스레드가 이어질 경우 등) 처리
- [ ] 도우미 추가, 탈퇴 기능 (멘션을 통해)

**Comment by BasixKOR** [comment]
가이드 봇은 어느 인스턴스에 두게 되나요?

**Comment by tribela** [comment]
@BasixKOR 인스턴스별로 관리자가 토큰을 등록하는 멀티 계정으로 할 수도 있고 단일계정으로 어딘가에 둘 수도 있는데 그건 아직 생각 중입니다.

**Comment by sftblw** [comment]
봇은 최소한으로 사용하고 질문을 받아줄 자원봉사자 사람에게 연결해주는 건 어떨까요?
너무 많은 걸 알려주려고 하면 신규 유저 입장에서 좀 부담스러울 것 같아서요.

**Comment by BasixKOR** [comment]
@sftblw 제 생각에는 가이드 봇은 "마스토돈에 관한 모든 정보를 알려준다" 보다는 "필요한 게 있을 때마다 물어볼 수 있는 봇" 정도가 맞는 것 같아요. 키워드에 관하여 몇 가지 답장을 설정해두고 사용자분들이 직접 이용하실 수 있도록 안내하는 것도 좋을 거라 생각해요.

자원봉사자 형태라면 제가 전에 마스토돈에서 제안드린 것처럼 `가이드봇 요청 →봉사자에게 다이렉트 메시지 → 봉사자가 다이렉트에 답변 → 봉사자의 답변을 요청한 사용자에게 전달` 형태는 어떨까요?

**Comment by tribela** [comment]
DM을 보내서 포워딩 하는 방식 괜찮은 것 같네요. 대화 스레드만 잘 이어서 멘션 연결해 주면 되니까요

**Comment by BasixKOR** [comment]
그러면 지금까지의 의견을 종합해서 자주 질문하는 키워드는 모아서 미리 답변을 설정해두고, 나머지는 자원 봉사자 분들이 돌아가시면서 DM을 전달하는 형태로 하면 어떨까요? 역시 같은 질문을 여러 번 받는 건 자원 봉사자 분들께도 실례인 것 같고, 정리해두면 더 양질의 답변을 제공할 수 있을테니 각각의 장단점이 있을 거라 생각해요.

**Comment by tribela** [comment]
자동답변은 아무래도 자연어 처리도 좀 해야 하고 (예전에 짜 둔 라이브러리가 있긴 합니다만) 불만족스러울 가능성이 높기 때문에 일단은 보류하고 질문을 받은 도우미가 짧은 답과 함께 해당 가이드 페이지를 링크하는 게 좋을 것 같네요.

만약 도우미가 시간 안에 답을 하지 못하면 다음 사람에게 넘기는 방식이 좋을까요 아니면 도우미를 한번에 모두 멘션하는 게 좋을까요?

**Comment by tribela** [comment]
해당 이슈는 mstdn-kr/guide-bot#1‍로 넘어갑시다.
