### ISSUE TITLE
joinmastodon.org 번역

### ISSUE THREAD

**Issue by BasixKOR** [mstdn-kr/mastodon-kr#3]
현재 마스토돈 공식 웹사이트인 joinmastodon.org는 12개국 언어로 번역되어 있습니다. 한국어 번역을 추가한다면 새로운 유저들에게 도움이 되지 않을까요?

**Comment by BasixKOR** [comment]
https://source.joinmastodon.org/mastodon/joinmastodon

소스 코드가 마스토돈용 깃랩에 따로 있는 것 같네요 :( 이쪽에 계정을 만들어서 기여하는 쪽이 좋을까요?

**Comment by sftblw** [comment]
아... 지금 봤습니다.
갑자기 하고싶어져서 PR 넣어뒀습니다.
https://source.joinmastodon.org/mastodon/joinmastodon/merge_requests/22

**Comment by sftblw** [comment]
상기 PR은 반영되었고 추가 PR까지 반영되면 자동으로 한국어로 나올겁니다. 제가 놓친 게 좀 있네요...
https://source.joinmastodon.org/mastodon/joinmastodon/merge_requests/25

**Comment by sftblw** [comment]
이제 한글 나옵니다.
