### ISSUE TITLE
릴레이 서버 운영

### ISSUE THREAD

**Issue by unstabler** [mstdn-kr/mastodon-kr#4]
`relay.mastodon.kr` 도메인으로 한국어권 인스턴스의 릴레이 서버를 운영해볼까 싶습니다. 

# TODO

* 화이트리스트 설정 
* https://github.com/mstdn-kr/relay-docs 문서 채우기

**Comment by tribela** [comment]
릴레이에 대한 가장 큰 우려는 스팸인데(인스턴스를 세워 붙이는 것만으로 퍼트리는 범위가 강력) 화이트리스트 기반으로 가는 게 어떨까 싶네요.

**Comment by Mnkai** [comment]
스팸을 방지하는 방법이 있어야 한다는 거에 찬성이에요. 하지만 화이트리스트 기반으로 만들고 신청하는 사람에게 언제나 승인하는 방식으로 한다면 기계화 스팸은 막을 수 있겠지만, 의도적인 반달은 막기 힘들지 않을까요? 그렇다고 특정 규모 이상의 인스턴스를 대상으로 한다면 릴레이의 취지가 좀 퇴색되는 것 같고요. 스팸에 대응할 방법에 대해서 조금 더 고려해 봐야할 것 같아요.

**Comment by tribela** [comment]
한국어 인스턴스만 받도록 하고 (기타 언어권을 받아버리면 한국어 릴레이가 아니게 되므로) 그렇게 해도 스팸이 온다면 인스턴스 차원에서 각자의 정책으로 침묵, 정지, 미디어차단을 하면 되죠.

문제는 화이트리스트를 운영하는 방법인데 일단 지금의 릴레이는 블랙리스트나 화이트리스트 정책을 사용하질 못 해서 제가 운영하는 릴레이는 IP 기반으로 운영 중이에요. 필요하다면 소스코드 수정을 해야겠네요.

**Comment by Mnkai** [comment]
블랙리스트/화이트리스트 기능이 업스트림 릴레이 서버 코드에 구현되기 전까진 ip 기반 승인 정책을 사용하는것도 괜찮을 것 같아요. 서버가 더 늘어나는 걸 대비해서 추후에 서버의 도메인 주소 기반으로 승인하도록 (일정 주기로 dns를 조회해서 갱신) 개선하는것도 괜찮겠지만, 우선 지금은 서버가 적으니까요.

**Comment by BasixKOR** [comment]
릴레이 화이트리스트 요청은 다른 레포에서 하도록 할까요? mstdn-kr/relay 처럼요

**Comment by tribela** [comment]
@BasixKOR 그걸 깃헙에서 하는 건 너무 깃헙에 의존하는 거죠.. 그냥 해당 인스턴스 관리자가 릴레이 관리자에게 마스토돈에서 요청하면 돼요. 관리자 인증도 쉽게 되고 외부 의존도 없이요.

**Comment by tribela** [comment]
> @Mnkai : 서버가 더 늘어나는 걸 대비해서 추후에 서버의 도메인 주소 기반으로 승인하도록 (일정 주기로 dns를 조회해서 갱신) 개선하는것도 괜찮겠지만, 우선 지금은 서버가 적으니까요.

CDN을 붙인 경우 DNS 주소와 실제 서버의 주소가 달라서 그렇게 간단하지만은 않아요. 외부 요청에 대해 프록시를 물려 놓았을 수도 있구요.

**Comment by Mnkai** [comment]
@Kjwon15 꼭 마스토돈 서버의 도메인이 아니더라도 별도의 서브도메인 주소처럼 ddns와 같은 방식도 괜찮으니까요, 한번 승인 한 이후에 ip가 변경되어서 다시 변경요청을 하는 일이 좀 죄송스러워서 그래요.

**Comment by robin-maki** [comment]
제가 궁금했던 거라든가 하는 걸 다 말해주셔서 더 이상 물어볼 게 없네요😅 전 좋아요!

**Comment by unstabler** [comment]
일단 릴레이 서버를 세우긴 했는데, 화이트리스트로 어떻게 설정해야 할지 모르겠습니다.
타 릴레이 서버를 참고하여 https://relay.mastodon.kr 접속 시 https://github.com/mstdn-kr/relay-docs 내용을 띄우도록 했습니다. 
릴레이 등록 시 `https://relay.mastodon.kr/inbox` 로 등록해주시면 될 겁니다.

**Comment by unstabler** [comment]
- twingyeo.kr
- edge.twingyeo.kr 

릴레이에 연결해 두었습니다.

**Comment by tribela** [comment]
@unstabler 
```nginx
error_page 403 = @blacklisted;

allow a.b.c.d;  # IP
allow a.b.c.d/24;  # CIDR

deny all;

location @blacklisted {
    allow all;
    return 444;
}
```

**Comment by unstabler** [comment]
뭐지 왜 닫았지?!

**Comment by unstabler** [comment]
아무래도 잠결에 닫아버린 것 같아요.. 여튼 화이트리스트?를 오늘 중으로 적용해보려 해 볼게요.

**Comment by unstabler** [comment]
화이트리스트 적용하였습니다.

https://github.com/mstdn-kr/kr-relay/blob/master/acl.txt

* 각 도메인의 A, AAAA 레코드를 기준으로 판단하기 때문에 cloudflare 등의 프록시가 적용되어 있는 경우 따로 `ip:xxx.xxx.xxx.xxx` 형식으로 아웃바운드 IP를 기재해 주셔야 합니다.
